# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  makepdf:
    image: makepdf
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:5002  # HTTP
      - 5555:5555  # HTTPS
    volumes:
      - ./cert:/app/cert:ro  # Mount certificates read-only
